config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedback_forms, only: %i[new create]

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges, except: :show
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :file, :reason, :rule_value, presence: true
  validates :rule_type, presence: true, uniqueness: { scope: :rule_value }
  validates :rule_type, inclusion: { in: BadgeIssuance::RULES,
                                     message: I18n.t('activerecord.errors.messages.rule_type') }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[destroy update edit]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :file, :reason, :rule_type, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!
  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_header(badge)
    return 'Новый бейдж' if badge.new_record?

    "Редактирование бейджа: #{badge.name}"
  end

  def rules_type_values
    BadgeIssuance::RULES.map { |rule| I18n.t(:rules)[rule.to_sym] }
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td scope="row"><%= badge.name %></td>
  <td ><img src="<%= badge.file %>" class="img-thumbnail rounded-circle"
            width="100" height="100"></td>
  <td scope="row"><%= badge.reason %></td>
  <td class="aligh-middle">
    <%= link_to  t(".edit"), edit_admin_badge_path(badge) %>
  </td>
  <td class="aligh-middle"><%= link_to  t(".delete"), admin_badge_path(badge), method: :delete, data: {confirm: 'Вы уверены?'} %>
</tr>

app/views/admin/badges/_form.html.erb
<%= badge_header(@badge) %>
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name, id: :badge_name %>
  </p>

  <p>
    <%= form.label :file %>
    <%= form.text_field :file, id: :badge_file %>
  </p>

  <p>
    <%= form.label :rule_type %>
    <%= form.collection_select :rule_type, rules_type_values, :to_s, :to_s, prompt: true %>
  </p>

  <p>
    <%= form.label :rule_value %>
    <%= form.text_field :rule_value, id: :badge_rule_value %>
  </p>

  <p>
    <%= form.label :reason %>
    <%= form.text_area :reason %>
  </p>

  <%= form.submit %>
  <%= link_to t('.badges'), admin_badges_path %>
<% end %>

app/views/admin/badges/edit.html.erb
<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h1><%= t('.badges')%></h1>
<%= link_to  t('.add_badge'), new_admin_badge_path %>
<table class="table table-bordered mt-3">
  <thead>
  <tr>
    <th scope="col"><%= t('.name') %></th>
    <th scope="col"><%= t('.file') %></th>
    <th scope="col"><%= t('.reason') %></th>
    <th colspan="2"><%= t('.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <%= render @badges %>
  </tbody>
</table>

app/views/admin/badges/new.html.erb
<%= render 'form' %>