config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedback_forms, only: %i[new create]

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges, except: :show
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true

  scope :correct, -> { where(correct: true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :file, :reason, :rule_value, presence: true
  validates :rule_type, presence: true, uniqueness: { scope: :rule_value }
  validates :rule_type, inclusion: { in: BadgeIssuance::RULES,
                                     message: I18n.t('activerecord.errors.messages.rule_type') }
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true
end

app/models/feedback_form.rb
class FeedbackForm
  include ActiveModel::Model

  attr_accessor :email, :text

  validates :email, :text, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :gist_url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :current_questions, class_name: 'TestPassage', foreign_key: :current_question_id, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :author, class_name: 'User'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :time, presence: true

  scope :easy, -> { where(level: 1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :sort_descending, lambda { |category_title|
                            joins(:category).where(categories: { title: category_title })
                                            .order(title: :desc).pluck(:title)
                          }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: %i[create update]

  def accept!(answers_ids)
    self.correct_questions += 1 if correct_answer?(answers_ids)
    self.successful = true if successful?
    self.current_question = nil if end_time?

    save!
  end

  def completed?
    current_question.nil?
  end

  def success_rate
    (correct_questions / test.questions.count.to_f) * 100
  end

  def test_time
    created_at + test.time * 60
  end

  def end_of_test_time
    test_time - Time.current
  end

  def end_time?
    Time.current - created_at >= test.time * 60
  end

  def successful?
    success_rate >= 85
  end

  def current_question_index
    test.questions.order(:id).index(current_question) + 1
  end

  def progress
    (current_question_index.to_f / test.questions.count * 100).round
  end

  private

  def before_validation_set_first_question
    self.current_question = next_question
  end

  def correct_answer?(answers_ids)
    return false if answers_ids.nil?

    correct_answers.ids.sort == answers_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      self.current_question = test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: :author_id, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def test_passage(test)
    test_passages.order(id: :desc).find_by test_id: test.id
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!
  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found
  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    redirect_to tests_path
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_header(answer)
    return "Новый ответ для вопроса: #{answer.question.body}" if answer.new_record?

    "Редактирование ответа на вопрос: #{answer.question.body}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Date.current.year
  end

  def flash_class_style(flash_type)
    flash_type.eql?('alert') ? 'alert-danger' : 'alert-info'
  end

  def github_url(author, repo)
    link_to 'Репозиторий проекта', "https://github.com/#{author}/#{repo}", target: '_blank'
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_header(badge)
    return 'Новый бейдж' if badge.new_record?

    "Редактирование бейджа: #{badge.name}"
  end

  def rules_type_values
    BadgeIssuance::RULES.map { |rule| I18n.t(:rules)[rule.to_sym] }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    return "Новый вопрос для теста: #{question.test.title}" if question.new_record?

    "Редактирование вопроса теста: #{question.test.title}"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def success_rate_color
    @test_passage.successful? ? 'success' : 'fail'
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    return 'Новый тест' if test.new_record?

    "Редактирование теста: #{test.title}"
  end
end

app/views/admin/_admin_header.html.erb
<nav class="navbar navbar-light bg-light">
  <h1>
    <%= link_to  "Testguru", tests_path, class: 'navbar-brand'%>
    <span class="badge badge-secondary"><%= link_to  t('.admin_panel'), admin_tests_path, class: 'navbar-brand'%></span>
    <span class="badge badge-secondary"><%= link_to  t('.badge'), admin_badges_path, class: 'navbar-brand'%></span>
    <%= link_to  t('.gists'), admin_gists_path, class: 'navbar-brand'%>
  </h1>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome', email: current_user.email) %></b> |
      <%= link_to  t('.logout'), destroy_user_session_path, method: :delete %>
  <% end %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel | Testguru</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'admin/admin_header' %>
<div class="container">
  <%= render 'shared/flash' %>
  <%= yield %>
</div>
<%= render 'shared/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no ">
    <title>Testguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present?%>
  <%= content_tag(:div, class: 'resource-errors', data: { resource_id: resource.try(:id) }) do %>
    <h2><%= t('.header', count: resource.errors.count) %>:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
    <%= content_tag :p, message.html_safe, class: "alert #{flash_class_style(key)}", role: "alert" %>
<% end %>

app/views/shared/_footer.html.erb
 <footer class="fixed-bottom row justify-content-center ml-3">
   <div class="col-1"><%= current_year %></p></div>
   <div class="col">Fedor Mutovin</div>
   <div class="col-3">Приложение для прохождения тестов</div>
   <div class="col"><%= github_url('FedorMutovin', 'testguru') %></div>
   <div class="col-4">
     <a href="https://thinknetica.com/">
       "Учебный проект в онлайн-школе Thinknetica"</a>
   </div>
 </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <h1>
    <%= link_to  "Testguru", tests_path, class: 'navbar-brand'%>
    <% if current_user&.admin? %>
      <span class="badge badge-secondary"><%= link_to  t('.admin_panel'), admin_tests_path, class: 'navbar-brand'%></span>
    <% end %>
    <%= link_to t('.feedback'), new_feedback_form_path, class: 'navbar-brand' %>
    <%= link_to t('.badge'), badges_path, class: 'navbar-brand' %>
  </h1>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome', email: current_user.email) %></b> |
      <%= link_to  t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to  t('.log_in'), new_user_session_path %></b> |
      <%= link_to  t('.sign_up'), new_user_registration_path %>
    <% end %>
  </span>
</nav>