config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedback_forms, only: %i[new create]

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges, except: :show
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: %i[create update]

  def accept!(answers_ids)
    self.correct_questions += 1 if correct_answer?(answers_ids)
    self.successful = true if successful?
    self.current_question = nil if end_time?

    save!
  end

  def completed?
    current_question.nil?
  end

  def success_rate
    (correct_questions / test.questions.count.to_f) * 100
  end

  def test_time
    created_at + test.time * 60
  end

  def end_of_test_time
    test_time - Time.current
  end

  def end_time?
    Time.current - created_at >= test.time * 60
  end

  def successful?
    success_rate >= 85
  end

  def current_question_index
    test.questions.order(:id).index(current_question) + 1
  end

  def progress
    (current_question_index.to_f / test.questions.count * 100).round
  end

  private

  def before_validation_set_first_question
    self.current_question = next_question
  end

  def correct_answer?(answers_ids)
    return false if answers_ids.nil?

    correct_answers.ids.sort == answers_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      self.current_question = test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show update result gist]

  def show; end

  def create; end

  def result; end

  def gist
    request = GistQuestionService.new(@test_passage.current_question)
    request_result = request.call
    response = request.client.last_response
    gist_link = request_result.html_url

    redirect_to @test_passage

    if gist_link.present? && response.status.eql?(201)
      current_user.gists.create(question: @test_passage.current_question, gist_url: gist_link)
      flash[:notice] = t('.success', gist_link: view_context.link_to('Gist', gist_link))
    else
      flash[:alert] = t('.failure')
    end
  end

  def update
    if params[:answers_ids].nil?
      redirect_to result_test_passage_path(@test_passage)
    else
      @test_passage.accept!(params[:answers_ids])
      if @test_passage.completed?
        @badges = BadgeIssuance.new(@test_passage).give_badges
        @test_passage.user.badges.push(@badges) if @badges.present?
        TestsMailer.completed_test(@test_passage).deliver_now
        redirect_to result_test_passage_path(@test_passage)
      else
        render :show
      end
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def success_rate_color
    @test_passage.successful? ? 'success' : 'fail'
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title)%></h1>
<p>
  Количество правильных ответов: <%= @test_passage.correct_questions %>
  из <%= @test_passage.test.questions.count %>
</p>
<p class="<%= success_rate_color %>">
  Процент успеха: <%= "#{@test_passage.success_rate.round}%" %>
</p>
<% if @test_passage.successful? %>
  <p class="<%= success_rate_color %>">
    Тест пройден
  </p>
<% else %>
  <p class="<%= success_rate_color %>">
    Тест не пройден
  </p>
<% end %>
<%= link_to  "Вернуться к тестам", tests_path, method: :get %>

app/views/test_passages/show.html.erb
<h1>Прохождение теста <%= @test_passage.test.title %></h1>
<div class="card shadow-sm mt-4">
  <div class="card-header">
    <b>До конца теста осталось</b>
  </div>
  <div class="card-body">
    <%= content_tag :h1, class: 'text-center timer', data: { time: @test_passage.end_of_test_time } do %>
      <span class="minutes"></span>:<span class="seconds"></span>
    <% end %>
  </div>
</div>
<div class="progress">
  <%= content_tag :div, class: 'progress-bar', data: { progress: @test_passage.progress} do %>
  <% end %>
</div>
<p>Вопрос: <%= "#{@test_passage.current_question_index} из #{@test_passage.test.questions.count} "%></p>
<p>
  <%= @test_passage.current_question.body %>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answers_ids, @test_passage.current_question.answers,
                                  :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
    <% end %>
  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Следующий' %></p>
<% end %>