config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedback_forms, only: %i[new create]

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges, except: :show
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :current_questions, class_name: 'TestPassage', foreign_key: :current_question_id, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[destroy show update edit]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def edit; end

  def show
    @answers = @question.answers
  end

  def destroy
    test = @question.test_id
    @question.destroy
    redirect_to admin_test_path(test)
  end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question]
    else
      render :edit
    end
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    redirect_to tests_path
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    return "Новый вопрос для теста: #{question.test.title}" if question.new_record?

    "Редактирование вопроса теста: #{question.test.title}"
  end
end

app/views/admin/questions/_form.html.erb
<%= question_header(@question) %>
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %>
    <%= form.text_field :body, id: :question_body %>
  </p>

  <%= form.submit %>
  <%= link_to  "К тесту", admin_tests_path, method: :get %>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td scope="row"> <%= link_to question.body, admin_question_path(question), method: :get %> </td>
  <td> <%= link_to  "Изменить", edit_admin_question_path(question), method: :get %> </td>
  <td> <%= link_to  "Удалить", admin_question_path(question), method: :delete, data: {confirm: 'Вы уверены?'} %> </td>
</tr>

app/views/admin/questions/show.html.erb
<h1><%= @question.body %></h1>
<% if @answers.present? %>
  <table class="table table-bordered mt-3">
    <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col">Корректность</th>
      <th colspan="2">Действия</th>
    </tr>
    </thead>
    <tbody>
    <%= render @answers %>
    </tbody>
  </table>
<% else %>
  <p>Нет доступных ответов для теста</p>
<% end %>
<%= link_to  "Добавить ответ", new_admin_question_answer_path(@question)%>
<%= link_to  "Назад к тесту", admin_test_path(@question.test), method: :get %>